
[Ores]
	#Generate Void Crystal Ore?
	void = true
	#Generate Tin Ore?
	tin = true
	#Ruby ore spawn frequency
	#Range: 1 ~ 100000
	ruby_common = 25000
	#Generate Copper Ore?
	copper = true
	#Generate Ruby Ore?
	ruby = true

[Specializations]
	#Allow Multiple specializations per player in Multiplayer?
	paths_multi = false
	#Allow Multiple specializations per player in Singleplayer?
	paths_single = true

	[Specializations.Technomancy]
		#FE equal to 1 Temporal Entropy
		#Range: > 1
		fe_per_entropy = 50
		#Enable hardmode for the Gateway?
		#If true, dialing in chevrons only works if the beam alignment matches the chevron being dialed
		#Enable this if you want an extra challenge
		gateway_hard = false
		#Whether Technomancy machines should drop an item when overloaded
		drop_machine = false
		#Maximum time duration for recalling, in seconds. Set to -1 to disable limit, 0 to disable recalling
		#Range: -1 ~ 86400
		time_recall = 300
		#Allow time acceleration of Tile Entities?
		#Disabling this does not affect acceleration of normal entities or block ticks
		te_accel = true
		#Does the CCC require specifically a Time beam?
		ccc_req_time = true
		#Allow Temporal Entropy disasters from Technomancy?
		#If disabled, disasters create a small explosion instead
		flux_disaster = true
		#Should recalling restore previous health and hunger?
		#Recommended to disable this for PvP
		stat_recall = true
		#Destroy the CCC if Copshowium overfills the tank?
		#Disabling this will make the CCC much easier to use
		allow_overflow = true

	[Specializations.Alchemy]
		#Whether lightning bolts from atmospheric overcharging can spawn the 4 horsemen
		#Overriden by gamerules
		atmos_horses = true
		#Maximum charge for the atmosphere
		#Range: 0 ~ 2000000000
		charge_limit = 1000000000
		#Allow the full effect of Phelostogen?
		#If disabled Phelostogen lights a single small fire instead
		phel_effect = true
		#Range of Density Plates
		#Range: 0 ~ 128
		grav_range = 64
		#Level of effects from overcharging the atmosphere
		#0: No negative effects
		#1: Allow lightning strikes
		#2: Allow creeper charging
		#3: Allow lightning strikes & creeper charging
		#Range: 0 ~ 3
		atmos_effects = 3
		#Percentage of Stamp Mill progress to be lost on failure
		#Effectively nerfs ore-tripling
		#Range: 0 ~ 100
		mill_damping = 0
		#Whether to allow Ignis Infernum
		#If disabled, Ignis Infernum is still craftable, but it gets nerfed to Phelostogen level
		ignis_infernum = true
		#FE produced by one Voltus
		#Range: 0 ~ 100000
		voltus_power = 2000

[Internal]
	#Whether Enchantment beams have a chance to destroy items
	enchant_destroy = true
	#Lower values increase network lag but increases gear speed synchronization
	#Range: 0.05000000074505806 ~ 10.0
	predict_speed = 0.20000000298023224
	#Wipe internal per player dimension mappings on failure?
	#Only change this if you know what you're doing
	wipe_dim_map = false
	#Interval in ticks between gear network checks
	#Range: 100 ~ 2400
	network_time = 300

[Misc]
	#Enable overheat effects?
	#If false, all heat cable overheating effects are replaced with burning
	cable_effects = true
	#Minimum spring speed to hover with the Whirligig
	#If set at or above 10, gaining elevation with a Whirligig is disabled
	#Range: 1.0 ~ 100.0
	whirligig_hover = 6.0
	#Minimum spring speed to eliminate fall damage with the Whirligig
	#If set at or above 10, gaining the Whirligig can not eliminate fall damage, but can reduce it
	#Range: 1.0 ~ 100.0
	whirligig_safe = 4.0

[Balance]
	#FE generated by one unit of charge-alignment beam
	#Range: > 0
	fe_per_charge = 50
	#Multiplier for rotary energy loss
	#Range: 0.0 ~ 2.147483647E9
	rotary_loss = 1.0
	#The maximum speed on a Spring Gun
	#Higher maximum speeds increase maximum damage
	#Range: 1.0 ~ 100.0
	spring_gun_cap = 10.0
	#The number of degrees one bucket of steam is worth
	#If this is changed, it is recommended to rebalance JSON recipes with steam
	#Range: > 0
	steam_value = 50
	#FE generated from 1J. Set to 0 to effectively disable the dynamo
	#Range: > 0
	dynamo_efficiency = 2
	#Resistive power exerted by the Winding Table per speed of the wound item
	#Range: 0.0 ~ 1000.0
	winding_resist = 20.0
	#Power generated by the Crystal Master Axis in J/t
	#Range: 0.0 ~ 2.147483647E9
	crystal_power = 100.0
	#The number of Joules generated from one degree worth of steam
	#Range: > 0
	joule_value = 4
	#Whether beams decide what they can pass through based on beam power
	#If true, low power beams require a smaller hole, and high power beams require a larger empty space in blocks to pass through
	beam_collision_use_power = false
	#The maximum speed a Stirling Engine can reach
	#Range: 0.0 ~ 2.147483647E9
	stirling_limit = 1.0
	#Multiplier for Stirling Engine power output
	#Range: 0.0 ~ 2.147483647E9
	stirling_multiplier = 2.5
	#Power divider for potential beams grow effect
	#For example, 2 will cause twice as much beam power for the same effect
	#Range: 1 ~ 64
	grow_divider = 1
	#Whether to destroy items when failing to wind them in a Winding Table
	winding_destroy = true

